### ISSUE TITLE
Add debug display information

### ISSUE THREAD

**Issue by pascalberger** [bbtsoftware/BBT.Maybe#59]
We should add information what debugger should be shown to Maybe type. See [Enhancing Debugging with the Debugger Display Attributes](https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/enhancing-debugging-with-the-debugger-display-attributes)

**Comment by marco-bertschi** [comment]
Questionable if here is something to do: [MaybeStruct](https://github.com/bbtsoftware/BBT.Maybe/blob/develop/src/BBT.MaybePattern/MaybeStruct.cs) and [Maybe](https://github.com/bbtsoftware/BBT.Maybe/blob/develop/src/BBT.MaybePattern/Maybe.cs) both have their `ToString` method overwritten which displays the Maybe's contained value (if set) already in the debugger window.

**Comment by marco-bertschi** [comment]
As mentioned above, the debugger display already works:
![image](https://user-images.githubusercontent.com/25186516/77739460-d3e55b00-7011-11ea-8c5c-b7bc2608e471.png)

Therefore closing this.
