### ISSUE TITLE
Build fails: https://www.myget.org/F/cake/api/v3/index.json: Package 'Cake.0.32.1' is not found on source

### ISSUE THREAD

**Issue by marco-bertschi** [bbtsoftware/BBT.Maybe#70]
At the moment, locally running `./build.ps1` fails for me:

> PS D:\_repo\BBT.Maybe> ./build.ps1
> Preparing to run build script...
> Unable to find version '0.32.1' of package 'Cake'.
>  C:\Users\xx\.nuget\packages\: Package 'Cake.0.32.1' is not found on source 'C:\Users\xx\.nuget\packages\'.
  https://www.myget.org/F/cake/api/v3/index.json: Package 'Cake.0.32.1' is not found on source 'https://www.myget.org/F/cake/api/v3/index.json'.

> An error occured while restoring NuGet tools.
> In D:\_repo\BBT.Maybe\build.ps1:166 Zeichen:9
>          Throw "An error occured while restoring NuGet tools."
>          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (An error occure...ng NuGet tools.:String) [], RuntimeException
    + FullyQualifiedErrorId : An error occured while restoring NuGet tools.

**Comment by marco-bertschi** [comment]
The same happens also on [AppVeyor](https://ci.appveyor.com/project/BBTSoftwareAG/bbt-maybe/builds/30374368)

**Comment by pascalberger** [comment]
Cake is no longer available through MyGet. I can update the boostrapper later to fix this.

**Comment by marco-bertschi** [comment]
Thanks, you can add me as reviewer if you wish.
I'll check the other repositories and create PRs there once I've seen what you changed,
